# Generated by Django 5.0.5 on 2024-05-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, null=True)),
                ('completo', models.BooleanField(default=False)),
                ('criado', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Tarefas',
                'verbose_name_plural': 'Tarefa',
                'ordering': ['criado'],
            },
        ),
    ]
