# Generated by Django 5.0.5 on 2024-05-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tarefa_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
